### ISSUE TITLE
crash when connecting to the ESB

### ISSUE THREAD

**Issue by owingruters** [telstrapurple/PurpleExplorer#39]
Hi,

I tried your tool but it crashed without any message, the second I connect with a connstring like this
Endpoint=sb://blabla.servicebus.windows.net/;SharedAccessKeyName=my-queue-access;SharedAccessKey=blablablablabla;EntityPath=my-queue

**Comment by owingruters** [comment]
I found the issue. You cannot use a conn.string to a specific queue or topic. Instead a con.string to the main workspace should be used

**Comment by rania-chantz** [comment]
@owingruters How should the correct string look like? Could you describe the format? I'm having the same issue. Thanks!

**Comment by armannaj** [comment]
The connection string you use should be the root connection string (which connects to the namespace), not the connection string to a specific queue or topic. 
The application needs the root connection string so that it can get the list of queues and topics and their data.
