### ISSUE TITLE
Message count on the queue/topic tree does not refresh after purging queue.

### ISSUE THREAD

**Issue by miqm** [telstrapurple/PurpleExplorer#41]
When you purge dead-letter queue, message count in brackets on the service bus structure tree does not get refreshed even if I hit "refresh button".

and is this project still maintained? it seems like this is the only UI tool that allows you to purge queues and subscriptions.

**Comment by armannaj** [comment]
Hi @miqm 
Thanks for reporting this issue. I'm looking into it.

**Comment by armannaj** [comment]
I've fixed it in #47
