### ISSUE TITLE
No support for Subscription Rules

### ISSUE THREAD

**Issue by irfan-visionet** [telstrapurple/PurpleExplorer#51]
Thanks a lot for this tool, but it lacks some key features.

- No support for message custom properties. No interface to view custom properties (when reading), and can't set those while sending a new message.
- It has support for topic and subscriptions, but support for subscription rules are missing. Rules are basically filters one can add to filter out messages for a specific subscription.
- Ref: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-resource-manager-namespace-topic-with-rule

**Comment by armannaj** [comment]
Thanks for reporting that, That would be a great feature but a big one. At this stage I'm not sure when/if I get a chance to implement that for now. Happy to review a PR if anyone else is interested.
