### ISSUE TITLE
PurpleExplorer only show the first 100 queues

### ISSUE THREAD

**Issue by jccorp** [telstrapurple/PurpleExplorer#52]
I'm connected to a SB with more than 100 queues and the app only shows the first 100.
![image](https://user-images.githubusercontent.com/812372/170080540-61a0395a-039b-4c80-a3ef-901112412e89.png)

**Comment by armannaj** [comment]
This is interesting, I was aware there is a default setting for that. 

I'm currently working on a settings page that we can configure this and some other options for the application.
