### ISSUE TITLE
Add Label/Subject column

### ISSUE THREAD

**Issue by adamal** [telstrapurple/PurpleExplorer#56]
This is how it looks in Azure portals Service Bus Explorer:

<img width="1389" alt="Screenshot 2022-06-07 at 11 07 10" src="https://user-images.githubusercontent.com/3245228/172343254-8032cc50-f692-415e-b32d-20d5f306d5cc.png">

And this is how it looks in VSCodes Service Bus Explorer extension:

<img width="1129" alt="Screenshot 2022-06-07 at 11 08 09" src="https://user-images.githubusercontent.com/3245228/172343387-2ed0af98-82e5-41a3-bea5-3356aee87236.png">

But the "Label" column is missing from Purple Explorer
<img width="924" alt="Screenshot 2022-06-07 at 11 07 53" src="https://user-images.githubusercontent.com/3245228/172343491-a28d1952-634e-4025-afa0-36d7d900fdbf.png">

The Label/Subject information is also not shown when opening messages individually.

**Comment by armannaj** [comment]
added it in v0.1.14
