### ISSUE TITLE
M1 chip error 

### ISSUE THREAD

**Issue by ClipClock08** [telstrapurple/PurpleExplorer#78]
Fatal error. Failed to load JIT compiler
<img width="260" alt="image" src="https://user-images.githubusercontent.com/7549179/223401875-80c4602d-d923-4ca6-bd31-14b8c1cb5616.png">

**Comment by LosManos** [comment]
I have an M2 and am presently running PurpleExplorer so above problem is solvable.

The bad news is that I don't remember exactly how; but it was a regular MacOS way.
The solution was something like realising Apple/MacOS doesn't recognise the application (the image you provided) and the adding the application to some "I trust this stuff" GUI.

I doubt this is a PurpleExplorer issue. Maybe something for the starter documentation though.

**Comment by fhaertig** [comment]
Had the same issue. The "I trust this stuff" GUI is actually at "Settings > Security & Data Protection" Tab "General". If you start the PurpleExplorer file and you see the error you posted, have a look at the mentioned Dialog - it will show a matching text saying something like "opening lib<xyz> denied" with a button "Allow". Just click this button a few times for every message which pops up and eventually, it will open!

**Comment by rvypandey** [comment]
Just adding screenshots to what @fhaertig mentioned (which is the way it worked for me)
![Uploading Screenshot 2023-11-27 at 6.31.47 PM.png…](Failed)
![Uploading Screenshot 2023-11-27 at 6.32.29 PM.png…](Allow here in System Settings > Privacy and Security)
